In [ ]:
import numpy as np


In [ ]:
## Arithmetic operation 

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
## matrix opreation

In [ ]:
x = np.array([[1, 2],
            [3, 4]])
y = np.array([[4, 3],
            [2, 1]])


print ("Array sum:\n", x + y)

print ("Array multiplication:\n", x*y)

print ("Matrix multiplication:\n", x.dot(y))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
# Trigonometric functions


In [ ]:
import cmath
x=np.array([2,3,5])
print(x)
print(np.sin(x))
print(np.cos(x))


y=np.array([0.8,0.6,0.7])
print(y)
print(np.arccos(y))
print(np.arcsin(y))
print(np.arctan(y))

[2 3 5]
[ 0.90929743  0.14112001 -0.95892427]
[-0.41614684 -0.9899925   0.28366219]
[0.8 0.6 0.7]
[0.64350111 0.92729522 0.79539883]
[0.92729522 0.64350111 0.7753975 ]
[0.67474094 0.5404195  0.61072596]
